#+TITLE: Summing up
#+DATE: <2025-06-16 lun>
#+TAGS[]: me work life
#+SONG: Nobody's Fault But My Own ⋅ Beck

It is perhaps a bit strange to start a blog by summing things up… but it is
still a starting point.

** Current status
I'm 44 years old and I've been a software developer for 25 years. 10 years ago,
I started a consulting and development company. I thought it was the best way to
do what I loved: solving other people's problems with creativity, intelligence
and elegance.

It turns out it's not what I expected: money always gets in the way, so you end
up doing stuff you don't like or picking projects you don't care much about.  I
think it's part of the consulting way: being able to work on what you love is
quite a luxury these days.

Of course, there were also happy times. We worked on really interesting
projects, on topics that I'd never dreamed of dealing with, with fun mental and
technical challenges,

Yes, reader, this is a "down" moment for me.

** What to do about it
When difficulties arise, I usually "play dead" ([[https://en.wikipedia.org/wiki/Apparent_death][thanatosis]]), and wait for the
events to solve. This behavior is probably the cause of many of my life
discontent.

Not this time.

I'm going to focus on my health, on my studies, and on producing something
meaningful to me. Also, I'll try my best to have fun again.

There are a lot of possibilities out there, I just have to choose and, more
importantly, stop being passive.

I'm going to keep this blog updated once a week to keep track of my progress,
sharing my journey along the way.
