services:
  mds-site:
    image: ghcr.io/mdallastella/mds-site:latest
    container_name: mdssite
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mdssite.entrypoints=websecure"
      - "traefik.http.routers.mdssite.rule=Host(`marco.dallastella.name`)"
      - "traefik.http.routers.mdssite.service=mdssite"
      - "traefik.http.services.mdssite.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=false"

networks:
  proxy:
    external: true
