#+TITLE: Week 35 and 36
#+DATE: <2025-09-07 Sun>
#+TAGS[]: work life
#+SONG: Seas of Cheese ⋅ Primus

** Personal life
The last couple of weeks have been pretty boring; not much has happened. I'm
starting to get a bit fed up with some unresolved matters.

I finished "Gone" and, since I don't have a real alternative, I started "Hunger"
from the same series. It's easy to read but boring—perfect for bedtime.

I'm doing more gardening; I enjoy doing something with my hands other than
pressing keys on a keyboard. It makes me feel real.

** Code
In my free time, I'm working on an RSS-to-Mastodon project with [[https://babashka.org/][Babashka]] to
automatically toot my posts to [[https://functional.cafe][Functional Cafe]].

I'm searching for an alternative to Vue to use with the Python project I'm
working on. [[https://htmx.org/][HTMX]] and [[https://data-star.dev/][Datastar]] sound promising, but the fact that you have to
send HTML over WebSockets or Server-Sent Events (SSE) feels off to me…
Applications should send and receive data, not fragments of HTML (which is data,
I know).

I've always been told to decouple software parts to achieve maximum flexibility.

I probably don't yet understand which kinds of applications these frameworks are
best suited for.

** Notable links of the week
+ [[https://eca.dev/][ECA - Editor Code Assistant]]
+ [[https://martinfowler.com/articles/202508-ai-thoughts.html][Some thoughts on LLMs and Software Development]] - Martin Fowler
+ [[https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/][Measuring the Impact of Early-2025 AI on Experienced Open-Source Developer Productivity]]
