#+TITLE: Week 37
#+DATE: <2025-09-14 Sun>
#+TAGS[]: work life
#+SONG: Heaven Knows I'm Miserable Now ⋅ The Smiths

** Personal life
Another boring week. I finished "Hunger" and started "Lies". Like the other two
books, it's not that deep, but I started to care for a couple of characters, so
I'm curious to see how the book goes. This third book is also interesting also
because "religion" is the main theme: different views on faith fighting each
other… I've always been fascinated with the concept, even if my "rational" mind
refuses any sort of faith. I'm still resonate with [[https://en.wikipedia.org/wiki/Jiddu_Krishnamurti][Jiddu Krishnamurti]] when he said:

#+begin_quote
I maintain that truth is a pathless land, and you cannot approach it by any path
whatsoever, by any religion, by any sect. That is my point of view, and I adhere
to that absolutely and unconditionally. Truth, being limitless, unconditioned,
unapproachable by any path whatsoever, cannot be organized; nor should any
organization be formed to lead or coerce people along a particular
path. …This is no magnificent deed, because I do not want followers, and I
mean this. The moment you follow someone you cease to follow Truth.
#+end_quote

Truth is a process, not a goal.

** Code
Clojure still amazes me, even after more than ten years: the community continues
to produce wonderful stuff… It's inspirational.

I gave up on Rust; I have no use at the moment for low-level code. And even if I
need some, I think I'll take a look at [[https://ziglang.org/][Zig]].

I'd like to try again with music frameworks like [[https://tidalcycles.org/][TidalCycle]] or [[https://overtone.github.io/][Overtone]].

I've been following the [[https://helix-editor.com/][Helix editor]] for a while now; I like the [[https://kakoune.org/][Kakoune]] modal
editing philosophy, and I'm really excited by its plugin system based on [[https://github.com/mattwparas/steel][Steel]]
(a Scheme interpreter written in Rust). There are some people against this
decision, and I expressed myself in the discussion on Github:

- [[https://github.com/helix-editor/helix/discussions/13464][Using Lisp dialect as a language of choice for plugin system is a bad decisio...]]

** Notable links of the week
+ [[https://drewdevault.com/2021/01/20/FOSS-is-to-surrender-your-monopoly.html][Open source means surrendering your monopoly over commercial exploitation]]
+ [[https://github.com/edent/SuperTinyIcons][GitHub - edent/SuperTinyIcons: Under 1KB each! Super Tiny Icons are miniscule...]]
+ [[https://philome.la/johnayliff/seedship/play/index.html][Seedship]] (Game)
+ [[https://www.infoq.com/presentations/Clojure-Expression-Problem/][Clojure's Solutions to the Expression Problem - InfoQ]]
