#+TITLE: Week 29
#+DATE: <2025-07-20 Sun>
#+TAGS[]: work life
#+SONG: Accade ⋅ C.S.I.

This is a summary of week 29, 2025:

This week went quite smoothly, but not really productive, with some hiccups here
and there. Next week I'll be on holiday, I hope to free my mind for a few days.


** No news, good news?
So, I don't have a lot to say about this week.

I dug a little deeper in k8s. I had to deal with it sometimes in the past,
but there were always one or two persons on the team dedicated to the
infrastructure. For this client, there is only one person, and he's not
constantly on the project, so I have to figure out some stuff for myself.
Still, I don't understand the reason for using k8s for a 200-300 users at max.

** Back to Niri
The biggest news is that I decided to give [[https://github.com/YaLTeR/niri][Niri]] another try this week, since
I had a little free time. My current work setup is:

- *Hardware*: Thinkpad T14s G3, two 27" monitors, Cable Matters dock
- Arch Linux (btw®), with LUKS and Btrfs, and [[https://wiki.archlinux.org/title/REFInd][rEFInd]]
- [[https://codeberg.org/fairyglade/ly][Ly]] as display manager
- Niri as window manager, [[https://github.com/lbonn/rofi][rofi]] as launcher, and [[https://github.com/Alexays/Waybar/][waybar]] as topbar. I'd really
  like to use [[https://github.com/elkowar/eww][eww]], let's see when I get further free time
- Holy Emacs is my main editor, [[https://sw.kovidgoyal.net/kitty/][kitty]] as terminal emulator

I'm going to use this configuration for a while, take notes and report back on
its usability.
