#+TITLE: Week 38
#+DATE: <2025-09-21 Sun>
#+TAGS[]: work life
#+SONG: Epitaph ⋅ King Crimson

** Personal
Another boring week, the weather in Italy has been nice but between work
and personal issues I didn't have time to enjoy it. I did some gardening on the
weekend, so it was "work" plus "fun".

I'm still going on with the "Gone" series: after "Hunger", I started with
"Plague". I have to admit that, against my predictions, the series gets darker and
more mature as it goes. As someone said "What would happen if Stephen King wrote
Lord of the Flies?"

I haven't mentioned yet that I own a Steam Deck. I used to own
a PS4 and a PS5, and the only games I played were [[https://en.wikipedia.org/wiki/Destiny_(video_game)][Destiny]] and [[https://en.wikipedia.org/wiki/Destiny_2][Destiny 2]], so
quite a casual gamer. Some [[https://en.wikipedia.org/wiki/Call_of_Duty][COD]] and [[https://en.wikipedia.org/wiki/Warframe][Warframe]] as well.

Then one day I thought I was wasting my time, and time is precious: I sold the
PS5 and bought a Steam Deck. Mostly because:

+ It's a handheld device; I can play everywhere inside and outside the house.
+ It has a battery, which naturally limits my playtime.
+ It runs Arch Linux :smile:

These days I mostly play another great love of mine, [[https://en.wikipedia.org/wiki/Titanfall_2][Titanfall 2]]. However, I think
I'm going to start playing something cozier and more immersive, like [[https://en.wikipedia.org/wiki/Cult_of_the_Lamb][Cult of the
Lamb]] or [[https://en.wikipedia.org/wiki/No_Man%27s_Sky][No Man's Sky]].

** Code
Last week was full of supply-chain attacks on NPM, and the situation is quite
scary. I don't know all the details, but something certainly needs to change. The
constant updates and "new features," the lack of code verification, and the
complete absence of big companies—who make billions relying on plenty of open
source code without bothering to contribute—are all concerning. We programmers,
as well, have responsibilities when we publish our code.

I don't know, the Gordian knot here is: how can we produce high-quality code and
let people enjoy it freely without being paid?

Who are these wonderful people who "sacrifice" themselves to provide free
code for us, asking for nothing in return, nor seeking help or support?

Is this sustainable in the long run? I think we will get an answer soon.

** Notable links
+ [[https://pmc.ncbi.nlm.nih.gov/articles/PMC11513550/][Practical guide to SHAP analysis: Explaining supervised machine learning model predictions in drug development - PMC]]
+ [[https://github.com/cloudstreet-dev/Lisp-in-2025][Lisp in 2025: A Practical Guide to the One True Programming Language]]
+ [[https://behavioralscientist.org/why-we-spiral/][Why We Spiral - by Gregory M. Walton - Behavioral Scientist]]
+ [[https://www.jeffgeerling.com/blog/2025/cubesats-are-fascinating-learning-tools-space][CubeSats are fascinating learning tools for space | Jeff Geerling]]
